services:
  database:
    image: postgis/postgis:13-master
    restart: always
    volumes:
      - ${VOLUME_PATH_PREFIX}/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: "directus"
      POSTGRES_DB: "directus"
    healthcheck:
      test: [ "CMD", "pg_isready", "--host=localhost", "--username=directus" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  cache:
    image: redis:6
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "[ $$(redis-cli ping) = 'PONG' ]" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  directus:
    image: directus/directus:latest
    restart: always
    ports:
      - 8055:8055
    volumes:
      - ${VOLUME_PATH_PREFIX}/uploads:/directus/uploads
      - ${VOLUME_PATH_PREFIX}/extensions:/directus/extensions
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
    environment:
      SECRET: ${DIRECTUS_SECRET}

      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "directus"

      CACHE_ENABLED: "true"
      CACHE_AUTO_PURGE: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://cache:6379"

      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
      WEBSOCKETS_ENABLED: "true"
      PUBLIC_URL: ${DIRECTUS_PUBLIC_URL}
      CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC: "https://modern-container.com"
      CORS_ORIGIN: "http://localhost:3000,https://modern-container.com"
